version: "3.7"

services:
  app:
    # served as a static file with https://hub.docker.com/_/nginx/
    build:
      context: ./services/app
      dockerfile: Dockerfile
    image: esio-streamlit:latest
    restart: always
    ports:
      - "8501:8501"
    networks:
      - esios_nw

networks:
  esios_nw:
    driver: bridge
