name: aiguasol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - jupyter
  - scikit-learn
  - seaborn
  - matplotlib
  - requests
  - marshmallow
  - streamlit
  - black
