name: esios-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - streamlit=1.3.*
  - matplotlib=3.5.*
  - numpy=1.21.*
  - pandas=1.3.*
  - requests=2.27.*
  - scikit-learn=1.0.*

